client_max_body_size 30M;

root /var/www/gramsetu;
index index.html;

location / {
    try_files $uri $uri/ /index.html;
}

location /downloads/ {
    try_files $uri =404;
}

location /api/ {
    include snippets/gramsetu-proxy.conf;
}

location /ws/ {
    include snippets/gramsetu-ws.conf;
}
